### ISSUE TITLE
implementar análise da voz passiva, média, recíproca e causativa

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#293]
\# sent_id = Avila2021:0:0:650
\# text = _**Uyupurungitá** pawa riré, **uyumusangawa** yepé ara **uyumunhã** arama mendarisawa kunhamukú ruka upé._
\# text_eng = After everything has been arranged, the day is set for the wedding to be celebrated in the girl's house.
\# text_por = Depois de ajustar-se tudo, marca-se o dia para ser celebrado o casamento na casa da moça.
\# text_source = Costa, 176-7, adap.
\# text_annotator = LFdeA

- [ ] implementar análise do prefixo _yu-_
- [ ] implementar análise do prefixo _mu-_
- [ ] rever análises prévias
- [ ] anotar mais exemplos

**Comment by leoalenc** [comment]
> \# sent_id = Avila2021:0:0:522
> \# text = _Tuyué ti wã urikú i awa, **uyupiruka** wã i akanga._
> \# text_eng = The old man no longer has hair, his head is already naked.
> \# text_por = O velho não tem mais cabelos, sua cabeça já está pelada.
> \# text_source = Hartt, 354, adap.
> \# text_annotator = LFdeA

**Comment by leoalenc** [comment]
> > # sent_id = Avila2021:0:0:522
> > # text = _Tuyué ti wã urikú i awa, **uyupiruka** wã i akanga._
> > # text_eng = The old man no longer has hair, his head is already naked.
> > # text_por = O velho não tem mais cabelos, sua cabeça já está pelada.
> > # text_source = Hartt, 354, adap.
> > # text_annotator = LFdeA

@juliana-gurgel e @dominickmaia , faz sentido incluir o exemplo original de Hartt (1938)?

**Comment by leoalenc** [comment]
> > > \# sent_id = Avila2021:0:0:522
> > > \# text = _Tuyué ti wã urikú i awa, **uyupiruka** wã i akanga._
> > > \# text_eng = The old man no longer has hair, his head is already naked.
> > > \# text_por = O velho não tem mais cabelos, sua cabeça já está pelada.
> > > \# text_source = Hartt, 354, adap.
> > > \# text_annotator = LFdeA
> 
> @juliana-gurgel e @dominickmaia , faz sentido incluir o exemplo original de Hartt (1938)? Ver discussão em #575 .

**Comment by juliana-gurgel** [comment]
> @juliana-gurgel e @dominickmaia , faz sentido incluir o exemplo original de Hartt (1938)?

Acredito que sim, professor @leoalenc, por conta da discrepância entre _ti_ e _intí_.

Hartt (1938, p. 354, No. 491):
> tuyaé intí uán orekó iaúa, yopiróg uán iakána.
> o velho já não tem cabelos, a cabeça dêle está calva.

O que acha, @dominickmaia ?

**Comment by leoalenc** [comment]
Etiqueta especial `=mid` não funciona com verbos incorporados:

```python
>>> s='''Paraná usuaxara: — Ah, yautí, iné ipú reyuyutima-putari/=mid mukũi/card wé!'''
>>> Yauti.pp(s)
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#25>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3366, in pp
    print(parseSentence(s).serialize())
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3111, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2638, in mkConlluSentence
    new=handleMiddlePassive(form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2035, in handleMiddlePassive
    parselist=getparselist(f"{entry['pref']}{entry['lemma']}")
KeyError: 'pref'
>>> s='''Paraná usuaxara: — Ah, yautí, iné ipú reyuyutima/=mid-putari mukũi/card wé!'''
>>> Yauti.pp(s)
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#27>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3366, in pp
    print(parseSentence(s).serialize())
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3109, in parseSentence
    tokens=splitMultiWordTokens(tokenize(sent))
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3065, in splitMultiWordTokens
    index=t.index(HYPHEN)
ValueError: substring not found
```

**Comment by leoalenc** [comment]
Relaciona-se com #698 .
