### ISSUE TITLE
forma ""opena-opena" de Hartt (1938)

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#445]
Postado em: https://github.com/dominickmaia/hartt/issues/8#issue-2384454691

> @Levymelo na página 591 temos _pena_, que pode ser "dobrar" ou "quebrar", que inclui a variação de Hartt "Hartt [pén]", eu pensaria então em usar "upena", ja que o "o" pro Hartt costuma ser prefixo de 3º pessoa SG ou manter a palavra original entre aspas, como fazemos quando tem uma palavra em português no meio da frase em nheengatu.

@Levymelo e @dominickmaia , de fato, existe essa esta entrada de Avila (2021):

`grep -EahwB 10 "pen" avila*.txt`
[...]
> **pena** (_v. intr._)  **1)** quebrar(-se): a) (no sentido de:) partir-se, romper-se, fraturar-se:  Apirú murumurú yú árupi, upena se pí upé. 
> (Hartt, 326, adap.) -  Pisei sobre o espinho do murumuru, ele quebrou no meu pé.;  Se apukuitawa upena. (Tastevin, 650, 
> adap.) -  Meu remo quebrou-se.;  Santá reté mirá, ti upena. (Hartt, 344, adap.) -  O pau é muito duro, não quebra.;  b) (no 
> sentido de:) ficar imprestável; inutilizar-se, danificar-se, enguiçar
> **2)** dobrar(-se)
>  ■ Reg. hist.: [Costa [pena], 202; Dias [upena], 573; Coudreau [opéna], 473; Seixas [upena], 64; Tastevin [pena], 650; Magalhães 
> [pêna], 60, 123; Stradelli [pena], 453; Hartt [pén], 326, 344] ● (do tupi pen) 

Vejam que alguns registros incluem _o_ ou _u_ como prefixo, a exemplo da forma empregada por Hartt. Por outro lado, tudo indica que se trata de forma reduplicada do verbo _pena,_ que, conforme o padrão regular das reduplicações de verbos (ver Cruz, Avila, Navarro), seria _upena-pena_. Adapatr como upena-upena e anotar então manualmente (o Yauti não consegue lidar com reduplicação no contexto da função de etiqueta  `/=mf`) com marca de `Style=Arch` e `ModernForm=upena-pena`. Ver https://github.com/CompLin/nheengatu/issues/436. 

```
>>> Yauti.getparselist("upena-upena")
[['upena-upena', None]]
>>> Yauti.pp("upena-upena")
1	upena-upena	pena	VERB	V	Person=3|Red=Yes|VerbForm=Fin	0	root	_	TokenRange=0:11


>>> Yauti.pp("upena-upena/=mf:m|upena-pena:x|v:h|v")
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#28>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2933, in pp
    print(parseSentence(s).serialize())
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2684, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2309, in mkConlluSentence
    modern_token=mkConlluToken(modern_form,modern_entries[0])
IndexError: list index out of range
```

https://github.com/dominickmaia/hartt/issues/8#issuecomment-2200878028

**Comment by leoalenc** [comment]
Relaciona-se com #775.

**Comment by leoalenc** [comment]
Anotação atual:
```conllu
# sent_id = Hartt1938:0:0:199
# text = Ne ruá i apixaĩ ã, upena-upena.
# text_por = Teu rosto está cheio de pregas.
# text_source = p. 333, No. 199
# text_orig = neruá iapixain an, open-open.
# text_eng = TODO
# text_orig_transcriber = Antônio Levy Melo Nogueira
# text_por_modernizer = Antônio Levy Melo Nogueira
# inputline = Ne ruá i/pron2 apixaĩ ã, upena-upena.
# text_annotator = Dominick Maia Alexandre
# reviewer1 = Leonel Figueiredo de Alencar
1	Ne	ne	PRON	PRON2	Case=Gen|Number=Sing|Person=2|Poss=Yes|PronType=Prs	2	nmod:poss	_	TokenRange=0:2
2	ruá	suá	NOUN	N	Number=Sing|Rel=Cont	4	nsubj	_	TokenRange=3:6
3	i	i	PRON	PRON2	Case=Gen|Number=Sing|Person=3|PronType=Prs	4	expl	_	TokenRange=7:8
4	apixaĩ	apixaĩ	ADJ	A	_	0	root	_	TokenRange=9:15
5	ã	ã	PART	PFV	Aspect=Perf	4	advmod	_	SpaceAfter=No|TokenRange=16:17
6	,	,	PUNCT	PUNCT	_	7	punct	_	TokenRange=17:18
7	upena-upena	pena	VERB	V	Mood=Ind|Person=3|Red=Yes|Style=Rare|VerbForm=Fin	4	parataxis	_	SpaceAfter=No|StandardForm=upena-pena|TokenRange=19:30
8	.	.	PUNCT	PUNCT	_	4	punct	_	SpaceAfter=No|TokenRange=30:31

```
