### ISSUE TITLE
inconsistência dos valores do atributo `OrigLang`

### ISSUE THREAD

**Issue by heliolbs** [CompLin/nheengatu#519]
Dentre as 97 ocorrências do atributo `OrigLang` no banco de árvores, há 95 com o valor `pt` e duas com o valor `por`. Esses valores são sinônimos, @leoalenc ? Se sim, devemos normalizá-los? Exemplos em `Cruz2011:0:0:40` e `Costa1909:1:52:52`:

`2	aula	aula	NOUN	N	Number=Sing	1	nsubj	_	OrigLang=pt|TokenRange=4:8`

`5	comadre	comadre	NOUN	N	Number=Sing	6	nmod:poss	_	OrigLang=por|TokenRange=24:31`

**Comment by leoalenc** [comment]
@heliolbs , obrigado por apontar esse erro. De fato, não há razão para valores divergentes. Estou pensando em uniformizar tudo com o código `por` de https://en.wikipedia.org/wiki/ISO_639-3, pois é bem provável que venhamos a nos deparar com situações de empréstimos _ad hoc_ e _code-switching_ (#512 ) de outras língua indígenas, as quais não estão contempladas nos códigos de duas letras de https://en.wikipedia.org/wiki/ISO_639-1.

**Comment by leoalenc** [comment]
@heliolbs , como você descobriu esse erro? Também seria muito interessante modelar no futuro o processo de detecção de erros ou inconsistências  no _treebank_. Parece que discrepâncias de frequências entre valores de um atributo constituem um indício importante. Se algo ocorre uma única vez ou muito pouco, tende a ser erro, me parece, dadas as mais de 1700 sentenças atuais do treebank. A IA gerativa daria algum suporte para automatizar essa investigação?

**Comment by leoalenc** [comment]
[OrigLang](https://universaldependencies.org/misc.html#origlang)
>Original language of the current token, if different from the main language of the file. Similarly to the Lang attribute, the value is the (lowercase) ISO 639 language code (ISO 639-1 if it exists, ISO 639-3 otherwise). However, unlike the Lang attribute, OrigLang does not switch the validator to the other language, i.e., the token must still adhere to the guidelines specific for the main language of the file.

**Comment by heliolbs** [comment]
> @heliolbs , como você descobriu esse erro?

@leoalenc , descobri esse erro durante minha investigação de como modelar um fluxograma do tratamento de palavras desconhecidas. Ao analisar o tratamento dos empréstimos, me veio a dúvida sobre a origem dos recebidos pelo nheengatu. Eu já tinha visto o atributo `OrigLang` nas consultas ao _treebank_, então fui investigar se havia hispanismos além de lusismos. Foi aí que encontrei as inconsistências.

> Também seria muito interessante modelar no futuro o processo de detecção de erros ou inconsistências no _treebank_. Parece que discrepâncias de frequências entre valores de um atributo constituem um indício importante. Se algo ocorre uma única vez ou muito pouco, tende a ser erro, me parece, dadas as mais de 1700 sentenças atuais do treebank.

Com certeza, @leoalenc . E esse é um dos problemas que eu queria abordar com a biblioteca de visualização mencionada na questão [#4](https://github.com/heliolbs/tese/issues/4) do meu repositório privado: há espaço para a automatização de inúmeros aspectos de verificação do _treebank_. Não apenas a consistência dos metadados, mas também a consistência de `upos`, `xpos`, `deprel` e de outros aspectos da tabela CoNLL-U em si.

> A IA gerativa daria algum suporte para automatizar essa investigação?

Daria sim, @leoalenc , mas o gargalo seria o limite de caracteres do contexto que os modelos disponíveis aceitam. Com o avanço da eficiência das abordagem adotadas tanto nas versões gratuitas quanto nas pagas, a quantidade de caracteres de contexto tem aumento significativamente: 1024, 2048, 4096 etc. Entretanto, nosso banco de árvores já tem quase 34 mil linhas. Posso estar enganado, mas acho que seria necessário pagar planos de acesso a recursos de LLM para sermos capazes de inserir um arquivo desse tamanho. A não ser que dividíssemos em vários arquivos menores. Ainda assim, talvez fosse necessário todo um fluxo de trabalho para organizar a tarefa. De todo modo, é uma questão que merece sim investigação por causa da expectativa de grande crescimento do banco.

**Comment by leoalenc** [comment]
- [ ] `pt` --> `por` como valor de `OrigLang` no _treebank_
- [ ] fazer substituição análoga no Yauti

**Comment by leoalenc** [comment]
As principais etiquetas especiais para tratamento de palavras desconhecidas admitem, no caso de empréstimos _ad hoc_, i.e., não dicionarizados em Avila (2021), especificação da língua doadora ou língua de partida (_source language_) bem como a forma original da palavra, no caso de forma divergente no texto nheengatu. A especificação da língua doadora deve consistir de [código ISO de língua de dois ou três caracteres](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes). Alguns exemplos fictícios:

```python

>>> s='Taína uú Apfelstrudel/=n:o|de.'
>>> Yauti.pp(s)

1	Taína	taína	NOUN	N	Number=Sing	2	nsubj	_	TokenRange=0:5
2	uú	ú	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=6:8
3	Apfelstrudel	apfelstrudel	NOUN	N	Number=Sing	2	obj	_	OrigLang=deu|SpaceAfter=No|TokenRange=9:21
4	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=21:22
```

```python
>>> s='Taína umupena i/pron2 manha smartwatch/=n:o|eng.'
>>> Yauti.pp(s)

1	Taína	taína	NOUN	N	Number=Sing	2	nsubj	_	TokenRange=0:5
2	umupena	mupena	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=6:13
3	i	i	PRON	PRON2	Case=Gen|Number=Sing|Person=3|Poss=Yes|PronType=Prs	4	nmod:poss	_	TokenRange=14:15
4	manha	manha	NOUN	N	Number=Sing	5	nmod:poss	_	TokenRange=16:21
5	smartwatch	smartwatch	NOUN	N	Number=Sing	2	obj	_	OrigLang=eng|SpaceAfter=No|TokenRange=22:32
6	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=32:33
```

```python
>>> s='Taína uú yakisoba/=n:o|jap.'
>>> Yauti.pp(s)

Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#329>", line 1, in <module>
  File "/home/user/scripts/AnnotateConllu.py", line 3095, in pp
    print(parseSentence(s).serialize())
  File "/home/user/scripts/AnnotateConllu.py", line 2845, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/user/scripts/AnnotateConllu.py", line 2329, in mkConlluSentence
    orig=get_iso_3_letter_code(orig)
  File "/home/user/scripts/AnnotateConllu.py", line 2096, in get_iso_3_letter_code
    raise ValueError(f"Invalid language code: {language_code}")
ValueError: Invalid language code: jap
```

```python
>>> s='Taína uú fejuada/=n:o|pt:s|feijoada.'
>>> Yauti.pp(s)

1	Taína	taína	NOUN	N	Number=Sing	2	nsubj	_	TokenRange=0:5
2	uú	ú	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=6:8
3	fejuada	fejuada	NOUN	N	Number=Sing	2	obj	_	Orig=feijoada|OrigLang=por|SpaceAfter=No|TokenRange=9:16
4	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=16:17


```

**Comment by leoalenc** [comment]
Estou reabrindo a _issue_ porque a documentação de UD é clara quando afirma que se deve usar o código de duas letras se existente. Essa lógica foi aplicada nos próprios prefixos dos nomes dos arquivos dos _treebanks_.
