### ISSUE TITLE
verificar na aplicação de etiquetas especiais se lema existe no léxico

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#549]
Esta _issue_ visa evitar problemas como o destacado no meu comentário abaixo relativo à forma _upetépetéka_, lematizada por @heliolbs como petéka por meio da aplicação de etiqueta especial.
- [x] quando da aplicação de etiquetas especiais, verificar, se a palavra não for de outra língua que não o nheengatu,  se lema existe no léxico

> ```
> 
> # text = [...] upetépetéka [...].
> 
> # text_orig = [...] opetépetéka [...].
> 
> # inputline = [...] upetépetéka/=red:l|4 [...].
> 
> 
> 
> 1	[...]	[...]	PUNCT	ELIP	_	2	punct	_	TokenRange=0:5
> 
> 2	upetépetéka	petéka	VERB	V	Mood=Ind|Person=3|Red=Yes|VerbForm=Fin	0	root	_	SpaceAfter=No|TokenRange=6:17
> 
> 3	[...]	[...]	PUNCT	ELIP	PunctType=Elip	2	punct	_	SpaceAfter=No|TokenRange=18:23
> 
> 4	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=23:24
> 
> ```
> 
> 
> 
> No exemplo acima, que recebeu uma correção de desvio de normalização ortográfica, temos um caso de reduplicação. Foi necessário usar o atributo obrigatório 'l' (de length) para indicar ao Yauti o trecho repetido. A base desse derivado já está no glossário.

@heliolbs , a adaptação ortográfica desse exemplo falhou. De fato, não existe a base com acento agudo no dicionário do Ávila (2021). A forma reduplicada parcialmente, portanto, não deve conter acento. A propósito, a reduplicação é um fenômeno muito importante em diversas línguas do mundo, incluindo as línguas amazônicas de modo geral e o nheengatu em particular. Recomendo que, na próxima reunião de vocês, sejam atribuídas tarefas a membros do grupo para expor sucintamente esse conteúdo na tese de Aline da Cruz (2011), que aprofunda bastante o mecanismo fonológico desse processo derivacional, e o tratamento mais simplificado de Navarro (2016). Recomendo também fazer uma busca textual no dicionário do Ávila (2021) pelas palavras-chave _reduplicação_ e _reduplicada_. Outra tarefa importantíssima pra próxima reunião de vocês seria @dominickmaia e @juliana-gurgel apresentarem os casos de reduplicação nas sentenças do banco de árvores provenientes diretamente de Hartt e Casasnovas, respectivamente. Finalmente, @heliolbs poderia fazer um levantamento das _issues_ a respeito de reduplicação, apresentando um resumo, postando alguma dúvida etc.

_Originally posted by @leoalenc in https://github.com/CompLin/nheengatu/issues/512#issuecomment-2338016161_

**Comment by leoalenc** [comment]
@heliolbs , veja esta nova funcionalidade que introduzi no Yauti:

```python

>>> Yauti.pp('[...] upetépetéka/=red:l|4 [...].')
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#745>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3230, in pp
    print(parseSentence(s).serialize())
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2980, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2552, in mkConlluSentence
    new=handlePartialRedup(form,length)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1994, in handlePartialRedup
    handleOrig(new,lemma,orig, orig_form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1947, in handleOrig
    _isInLexicon(lemma)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1935, in _isInLexicon
    raise Exception(f"Lemma '{lemma}' not found in the lexicon")
Exception: Lemma 'petéka' not found in the lexicon

```

**Comment by leoalenc** [comment]
@heliolbs , outros controles são feitos, verificando se a forma envolve _code-mixing_ ou _code-shift_ etc.:

```python
>>> AnnotateConllu.pp('Aintá/pron umunhã mujekawasú/=ev:x|n:s|mujica:o|pt:a|f.')
1	Aintá	aintá	PRON	PRON	Number=Plur|Person=3|PronType=Prs	2	nsubj	_	TokenRange=0:5
2	umunhã	munhã	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=6:12
3	mujekawasú	mujeka	NOUN	N	Degree=Aug|Number=Sing	2	obj	_	Orig=mujica|OrigLang=por|SpaceAfter=No|TokenRange=13:23
4	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=23:24


>>> AnnotateConllu.pp('Aintá/pron umunhã mujekawasú/=ev:x|n:o|pt:a|f.')
1	Aintá	aintá	PRON	PRON	Number=Plur|Person=3|PronType=Prs	2	nsubj	_	TokenRange=0:5
2	umunhã	munhã	VERB	V	Mood=Ind|Person=3|VerbForm=Fin	0	root	_	TokenRange=6:12
3	mujekawasú	mujeka	NOUN	N	Degree=Aug|Number=Sing	2	obj	_	OrigLang=por|SpaceAfter=No|TokenRange=13:23
4	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=23:24


>>> AnnotateConllu.pp('Aintá/pron umunhã mujekawasú/=ev:x|n:a|f.')
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#750>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3226, in pp
    print(parseSentence(s).serialize())
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2976, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2533, in mkConlluSentence
    new=mkEval(form,xpos,force,orig,orig_form,accent)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2152, in mkEval
    return mkNoun(lemma,dic=dic,orig=orig,orig_form=orig_form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2085, in mkNoun
    handleOrig(new,lemma,orig, orig_form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1947, in handleOrig
    _isInLexicon(lemma)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1935, in _isInLexicon
    raise Exception(f"Lemma '{lemma}' not found in the lexicon")
Exception: Lemma 'mujeka' not found in the lexicon
>>> AnnotateConllu.pp('Aintá/pron umunhã mujekawasú/=ev:x|n:s|mujica:a|f.')
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#751>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3226, in pp
    print(parseSentence(s).serialize())
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2976, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2533, in mkConlluSentence
    new=mkEval(form,xpos,force,orig,orig_form,accent)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2152, in mkEval
    return mkNoun(lemma,dic=dic,orig=orig,orig_form=orig_form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2085, in mkNoun
    handleOrig(new,lemma,orig, orig_form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1941, in handleOrig
    raise Exception(f"Original form '{orig_form}' without original language")
Exception: Original form 'mujica' without original language

```

**Comment by leoalenc** [comment]
Resolvido com https://github.com/CompLin/nheengatu/commit/c33b210c7a0d0a21dfdc5432cdac44f8a6ad64d0
