### ISSUE TITLE
problema na análise automática da reduplicação parcial em caso de "code mixing"

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#578]
- [x] etiqueta especial `=red` para análise automática da reduplicação parcial produz erro em caso de "code mixing"

```conllu
# sent_id = Cruz2011:0:0:119
# text = Ti maã aganaganari.
# text_eng = TODO
# text_por = Não enganaria.
# text_source = Example No. 1029 Wr
# text_orig = ti=maã a-gana~ganai
# text_annotator = Leonel Figueiredo de Alencar
# inputline = Ti maã/cond aganaganari.
1	Ti	ti	PART	NEG	PartType=Neg|Polarity=Neg	0	advmod	_	TokenRange=0:2
2	maã	maã	PART	COND	Mood=Cnd|PartType=Mod	0	advmod	_	TokenRange=3:6
3	aganaganari	aganaganari	_	_	_	0	_	_	SpaceAfter=No|TokenRange=7:18
4	.	.	PUNCT	PUNCT	_	1	punct	_	SpaceAfter=No|TokenRange=18:19
```
A aplicação da função `parseExample` sobre a _string_  `'Ti maã/cond aganaganari/=red:l|4.'` ou `'Ti maã/cond aganaganari/=red:l|4:o|pt:s|enganar.'` gera este erro:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#57>", line 1, in <module>
  File "<pyshell#56>", line 3, in pz
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2849, in parseExample
    output=handleSents(sents,pref,textid,index,sentid,annotator,metadata)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2720, in handleSents
    tk=parseSentence(sents[0])
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2997, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2564, in mkConlluSentence
    new=handlePartialRedup(form,length)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2009, in handlePartialRedup
    handleOrig(new,lemma,orig, orig_form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1961, in handleOrig
    _isInLexicon(lemma)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1949, in _isInLexicon
    raise Exception(f"Lemma '{lemma}' not found in the lexicon")
Exception: Lemma 'ganari' not found in the lexicon

```

**Comment by leoalenc** [comment]
Relaciona-se com #199 #155 #527 #512 #523 .

**Comment by leoalenc** [comment]
O problema já estava resolvido faz algum tempo. Estou fechando esta _issue_.

```python
>>> Yauti.pp('Ti maã/cond aganaganari/=red:l|4:o|pt:s|enganar.')
```
```conllu
1	Ti	ti	PART	NEG	PartType=Neg|Polarity=Neg	3	advmod	_	TokenRange=0:2
2	maã	maã	PART	COND	Mood=Cnd|PartType=Mod	3	advmod	_	TokenRange=3:6
3	aganaganari	ganari	VERB	V	Mood=Ind|Number=Sing|Person=1|Red=Yes|VerbForm=Fin	0	root	_	Orig=enganar|OrigLang=por|SpaceAfter=No|TokenRange=7:18
4	.	.	PUNCT	PUNCT	_	3	punct	_	SpaceAfter=No|TokenRange=18:19
```
