### ISSUE TITLE
incluir lemma verbal "yumumunéu" na adaptação do exemplo 209 de Hartt (1938)?

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#661]
- [x] incluir lemma verbal _yumumunéu_ na adaptação do exemplo 209 de Hartt (1938)?
 - [x] incluir o verbo _muamundéu_ no glossário
 - [x] incluir variante _muamunéu_ no glossário
       
> 209 - xasó xayumumunéu.
> 209 - Xasú **xayumuamundéu**. # forma adaptada para anotar e incluir no treebank
> 209 - Asú ayumuamundéu. (Hartt, 334, adap.) - Vou me vestir.
> 209 - Vou me vestir.
> 

_Originally posted by @dominickmaia in https://github.com/CompLin/nheengatu/issues/660#issuecomment-2506714415_

**Comment by leoalenc** [comment]
Avila (2021):

>**muamundéu** (_v. tr._)  **1)** vestir, colocar roupa em:  Remuamundéu ne raíra. -  Vista o teu filho.2) [hist.] disfarçar (Stradelli, 406)3) [hist.] calçar (Dias, 561)  ■   Reg.  hist.:  [Costa  [mamundeo,  muhamundeo],  195;  Stradelli,  [munhãmundé,  muamundé]  306,  [muamundé]  406, [muamundéu] 406; Rodrigues [yu moan mondéo], 139; Rodrigues (1894) [moã mondé], 25; Dias [muamoneú], 561; Hartt [yumumunéu], 334; Aguiar [muámámunê], 45; Amorim [iumuamundeu], 366] ● (do tupi moaomondeb [mo- + aoba + mondeb]

>**yumuamundéu** (_v. intr._)  vestir-se [obs.: tb. pode ser empregado como forma recíproca]:  Asú ayumuamundéu. (Hartt, 334, adap.) -  Vou me vestir.;  Yawé paá uyumuamundéu usú uikú, mairamé umbawa, aé umutumú i yuwá-itá, [...]. (Amorim, 366, adap.) -  Assim, contam, ele foi se vestindo, quando acabou, sacudiu os braços, [...].;  Kuíri peyumuamundéu wã. (Leetra Indígena. n. 17, 53, adap.) -  Agora se vistam. ■ Reg. hist.: [Stradelli, [iumunhãmundé] 306, [iumuamundé] 390; Rodrigues [yu moan mondéo], 139; Hartt [yumumunéu], 334; Amorim [iumuamundeu], 366] ◆ [der. de yu-, muamundéu]

@dominickmaia , considerando as entradas acima, temos duas opções para adaptar a forma _yumumunéu_ de Hartt (1938), mencionada entre os registros históricos dos dois verbetes acima. A primeira é simplesmente adotar o lema _yumuamundéu_, seguindo nossa política de escolher o lema mais próximo entre aqueles propostos por Avila (2021). Nesse caso, devemos usar a etiqueta de análise da voz médio-passiva (#548 #548 ):

```python
>>> s='''209 - xasó xayumumunéu.
209 - Xasú xayumuamundéu/=mid. # forma adaptada para anotar e incluir no treebank
209 - Asú ayumuamundéu. (Hartt, 334, adap.) - Vou me vestir.
209 - Vou me vestir.'''
>>> Yauti.parseExampleHartt(s,334,annotator=Metadata.PEOPLE['dom'],transcriber='lev')
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#402>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3890, in parseExampleHartt
    sent_nr=handled['index'][0]
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2854, in _parseExample
    tokenlist=_handleSents(sents,annotator,metadata)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2753, in _handleSents
    tokenlist=parseSentence(text)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3022, in parseSentence
    tk=mkConlluSentence(tokens)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 2582, in mkConlluSentence
    new=handleMiddlePassive(form)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1998, in handleMiddlePassive
    _isInLexicon(lemma='',parselist=parselist)
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 1957, in _isInLexicon
    raise Exception(f"Lemma '{lemma}' not found in the lexicon")
Exception: Lemma 'xamuamundéu' not found in the lexicon
```

**Comment by leoalenc** [comment]
Sentenças com verbo designativo de "vestir" na versão atual do arquivo `frases.txt`:

> 210 - xasó xamanéu se kamixá.
> 210 - Xasú xayumunéu se kamixá.
> 210 - Vou vestir minha camisa.
> 
> 211 - emuné uán neturína.
> 211 - Emunéu wã ne turina. # forma adaptada para anotar e incluir no treebank
> 211 - Remundéu wã ne turina. (Hartt, 334, adap.) - Veste já a tua calça.
> 211 - Veste já tua calça.

@dominickmaia , manéu  parece ser corruptela de _muamundéu_: _muamundéu_ -> _muamunéu_ (supressão de /d/ comum na variante descrita por Hartt) ->  _mamunéu_  -> _manéu_. Esses últimos passos são mera especulação minha.

**Comment by leoalenc** [comment]
@dominickmaia , eis abaixo a minha conclusão sobre a sentença 210. Você revisa e coloca seu nome de revisora.

```python
>>> s='''210 - xasó xamanéu se kamixá.
210 - Xasú xamanéu/=typo:c|xamunéu se kamixá.
210 - Vou vestir minha camisa.'''
>>> Yauti.parseExampleHartt(s,334,transcriber='lev')
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#405>", line 1, in <module>
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3870, in parseExampleHartt
    91 - Intí ã se kirimbá xasupiri arama maã i pusé reté waá.
  File "/home/leonel/Dropbox/scripts/AnnotateConllu.py", line 3349, in handleSentsHartt
    raise ValueError("Input string must contain exactly four non-empty lines.")
ValueError: Input string must contain exactly four non-empty lines.
>>> s='''210 - xasó xamanéu se kamixá.
210 - Xasú xamanéu/=typo:c|xamunéu se kamixá.
210 - NA
210 - Vou vestir minha camisa.'''
>>> Yauti.parseExampleHartt(s,334,transcriber='lev')

```
```conllu
# sent_id = Hartt1938:0:0:210
# text = Xasú xamanéu se kamixá.
# text_por = Vou vestir minha camisa.
# text_source = p. 334, No. 210
# text_orig = xasó xamanéu se kamixá.
# text_eng = TODO
# text_orig_transcriber = Antônio Levy Melo Nogueira
# text_por_modernizer = Antônio Levy Melo Nogueira
# inputline = Xasú xamanéu/=typo:c|xamunéu se kamixá.
# text_annotator = Leonel Figueiredo de Alencar
1	Xasú	sú	AUX	AUXFR	Mood=Ind|Number=Sing|Person=1|Style=Arch|VerbForm=Fin	2	aux	_	ModernForm=Asú|TokenRange=0:4
2	xamanéu	munéu	VERB	V	Mood=Ind|Number=Sing|Person=1|Style=Arch|Typo=Yes|VerbForm=Fin	0	root	_	CorrectForm=xamunéu|ModernForm=amanéu|TokenRange=5:12
3	se	se	PRON	PRON2	Case=Gen|Number=Sing|Person=1|Poss=Yes|PronType=Prs	4	nmod:poss	_	TokenRange=13:15
4	kamixá	kamixá	NOUN	N	Number=Sing	2	obj	_	SpaceAfter=No|TokenRange=16:22
5	.	.	PUNCT	PUNCT	_	2	punct	_	SpaceAfter=No|TokenRange=22:23




```

**Comment by leoalenc** [comment]
Sobre  _yumumunéu_, me parece que só razões fortes para incluirmos  _muamunéu_ como variante do lema **muamundéu**, derivada pelo processo de elisão de /d/ que inclusive permite relacionar _munéu_ a _mundéu_. Portanto, você pode usar a etiqueta =typo em combinação com a função para tratamento da voz médio-passiva, como vou mostrar noutra _issue_.
